### ISSUE TITLE
Thank You Note & Minor Comment On `poetry` Usage

### ISSUE THREAD

**Issue by AFg6K7h4fhy2** [arnor-sigurdsson/EIR#96]
(1) Thank you very much for EIR! 
(2) I expect to use EIR in the near-term future.
(3) I hope to provide user feedback on EIR.
(4) I found EIR through a series of links that begin initially with the desire I've had to reproduce _[Accurate Genomic Prediction of Human Height](https://academic.oup.com/genetics/article/210/2/477/5931053)_ (2017).
(5) I very much appreciate your use of `.pre-commit` and `poetry`!
(6) Feel free to ignore the following minor suggestions:

<details markdown=1>
<summary>
Some minor suggestions...
</summary

Consider moving `pytest` to `tool.poetry.group.test.dependencies`.

Consider removing `poetry.lock` from `git` tracking via: `git rm --cached poetry.lock` (after adding `poetry.lock` to your `.gitignore`).

Consider adding, to your `.gitignore`, some of the content in the default Python `.gitignore` found here <https://github.com/github/gitignore/blob/main/Python.gitignore>. 

Consider adding your GitHub account email or username to `authors` in `pyproject.toml`.

Consider using `ruff` in `pre-commit` (see [here](https://github.com/astral-sh/ruff-pre-commit)) instead of `flake8`. Also, [this article](https://daftdev.blog/2024/03/25/migrating-to-ruff-from-black-and-flake8/) can provide further context. 

(might be asking a lot) Consider using `polars` over `pandas` for the sake of speed.
</details>

(7) Again, thank you for your work; may this repository live a long and useful life!

_This issue may be deleted once read. Any accepted suggestions can be addressed in other issues._

**Comment by arnor-sigurdsson** [comment]
Hi! Thank you for your very nice comment and great points!

> Consider moving `pytest` to `tool.poetry.group.test.dependencies`.

Good point, currently I have it in `[tool.poetry.group.dev.dependencies]` but later I might make a separate group specifically for testing.

> Consider removing `poetry.lock` from `git` tracking via: `git rm --cached poetry.lock` (after adding `poetry.lock` to your `.gitignore`).

Fair point, but I think I will keep it for now to allow for reproducible environments, e.g., when cloning the repository.

> Consider adding, to your `.gitignore`, some of the content in the default Python `.gitignore` found here https://github.com/github/gitignore/blob/main/Python.gitignore.

Good suggestion, I have updated the `.gitignore` file with some things I was missing from that link, thanks!

> Consider adding your GitHub account email or username to `authors` in `pyproject.toml`.

Thanks, added some more information to `pyproject.toml`.

> Consider using `ruff` in `pre-commit` (see [here](https://github.com/astral-sh/ruff-pre-commit)) instead of `flake8`. Also, [this article](https://daftdev.blog/2024/03/25/migrating-to-ruff-from-black-and-flake8/) can provide further context.

For now, `flake8` is actually quite snappy for my use case, but `ruff` is definitely something I have been keeping on my radar for potential future use.

> (might be asking a lot) Consider using `polars` over `pandas` for the sake of speed.

Yes, this is also something I have been considering, specifically for potentially speedup in reading large `.csv` files. For now, I have been experimenting with using the `pyarrow` backend in `pandas`, but might look into switching some parts to using `polars` later when I have time.

Thank you for your kind words and suggestions that help me improve the project!
